
													# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
													indent_style = "Visual"
													use_small_heuristics = "Max"
													wrap_comments = false
													condense_wildcard_suffixes = true
													brace_style = "PreferSameLine"
													enum_discrim_align_threshold = 100
													fn_single_line = true
													where_single_line = true
													format_macro_matchers = true
													format_macro_bodies = true
													hard_tabs = true
													imports_indent = "Visual"
													merge_imports = true
													max_width = 1200
													merge_derives = true
													struct_field_align_threshold = 100
													use_field_init_shorthand = true
													use_try_shorthand = true
													unstable_features = true
													edition = "2018"
													version = "Two"
													reorder_imports = false
												